### ISSUE TITLE
Question Regarding xdp multiprog and suricata

### ISSUE THREAD

**Issue by CyberTaoFlow** [vincentmli/suricata#1]
Hello,  Great work here. 

While researching some XDP implementation troubles relating to suricata i came across your excellent and insightful work and wanted to reach out primarily to commend your work on this (XDP-Suricata) subject.

Secondarily I wanted to ask if you can think of any reason not to take advantage of this edge case you reported - https://redmine.openinfosecfoundation.org/issues/6731

As a means of providing xdp multiprog support by pre-empting suricata's prog load using xdp-loader to load the suricata provided bpf progs and any others prior to starting suricata.

Based on my understanding of the issue (6731) above if suricata finds existing pinned-maps it wont attempt to load the program anyway right?   Provided that bpf-fs is available and the maps are usable will it continue updating them with bypass eligible flows?

I plan to present this same question to the suricata dev's but me being an autodidact much like yourself I felt a certain kinship i wanted to express....

Thanks!

**Comment by vincentmli** [comment]
@CyberTaoFlow thanks :) I have been working on some other project and I think now I may have time come back to this, yes, I think suricata could use libxdp to load the xdp program to work well with other xdp program.

**Comment by CyberTaoFlow** [comment]
Thanks for replying I will close this now but may re-open ....
